name: BUILD

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build Docker image
      - run: docker build -t buildserver .

      # Đợi 10 phút rồi tiếp tục chạy lại chính workflow này
      - run: |
          sleep 600 # 10 phút = 600 giây
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
               -d '{"ref":"main"}'
